services:
  init:
    image: python:3.9
    container_name: init
    volumes:
      - ./migrations:/migrations:ro
    environment:
      - DB_URL=postgresql://myuser:mypassword@postgres/mydatabase
    command:
      - sh
      - -c
      - |
        cd /migrations
        pip install poetry
        poetry lock --no-update
        poetry install
        poetry run python migrate.py
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
